FROM golang:1.16-alpine AS build_base

RUN apk add --no-cache git
WORKDIR /tmp/cache-service

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o  /usr/bin/cache-service .

LABEL maintainer="Michel Bongard"

ENTRYPOINT [ "/usr/bin/cache-service" ]
