apiVersion: v1
kind: ConfigMap
metadata:
  name: "cache-service-config"
data:
    ARANGO_ADDRESS: jalapeno-arangodb.jalapeno.svc.cluster.local:8086
    ARANGO_DB_NAME: jalapeno
    SENTINEL_ADDRESS: sentinel.jagw-dev-dominique.svc.cluster.local:5000
    SENTINEL_MASTER: mymaster
    KAFKA_ADDRESS: "kafka.jalapeno.svc.cluster.local:9092"
    LOG_LEVEL: trace